Wolg/awesome-swift

- README.md
R.swift is a tool that you integrate easily into your build process and generates a struct so you can reference resources strongly. Normally you would write `UIImage(named: "settings-icon")` but with R.swift you can type a compile time checked variant: `R.image.settingsIcon`.
Already saved us a lot of small errors and makes renaming stuff much easier! See: https://github.com/mac-cain13/R.swift
> Add R.swift to the misc list

- README.md
https://github.com/StephenHaney/Swift-Custom-Events
> add Swift-Custom-Events

- README.md
This library is written by me. I hope Swift can be fast enough to demonstrate its potential in finance area.
> Adding SwiftIB library

- README.md
https://github.com/tadija/AEXML
> Add AEXML parser

- README.md
Added UI auto-layout framework [Swiftstraints](https://github.com/Skyvive/Swiftstraints).
> Include Swiftstraints

- README.md
Hi there!
Coshx Labs has just opened source that library. It would be great if you can add it to your repo!
Cheers!
> Adds Caravel to Event section

- README.md
Add a new entry on HTTP  with AeroGear library. It make work with Rest APIs very easy.
> Adds contribution on HTTP Section

- README.md
LNRSimpleNotifications is a simplified port of TSMessages, a very popular Objective-C in-app notifications library.
> Added LNRSimpleNotifications to UI libraries.

- README.md
At WeltN24 we made [Carlos](https://github.com/WeltN24/Carlos), a flexible cache library that lets you create complex cache infrastructures in a simple way. I would love to include it in this list.
> Adds Carlos to the Caching paragraph

- README.md
Library that introduces key-value coding to native Swift types.
> Add SwiftKVC

- README.md
This project was included in [SwiftSandbox's issue 9](http://swiftsandbox.io/issues/9)
> Added Fuzi, mentioned by SwiftSandbox issue 9

- README.md
Compass helps you setup a central navigation system for your application.
> Add Compass

- README.md
@Wolg Let me know if there's any issue in the syntax or the place where those libraries should go. Thanks!
> Added SwiftyButton, SwiftyRSA, and Kugel

- README.md
If there's anything wrong, let me know and I'll fix it!
> Add SwiftMongoDB

- README.md
* [HTYTextField](https://github.com/hanton/HTYTextField) - A UITextField with bouncy placeholder in Swift.
> Add HTYTextField

- README.md
Helping you find inner peace when comparing version numbers in Swift
> Add Versions to Misc

- README.md
https://github.com/xmartlabs/XLActionController
> Added XLActionController library

- README.md
This adds BFKit-Swift to Extensions section
> Add BFKit-Swift to Kit section

- README.md
Please take a look at Pull Request format
Here we have:
1) the short description of addition in our own words
2) link to the repository
3) example of component's work (code example, gif-animation or picture for UI) in separate commit comment
> Update README.md, Proposing a new Pull Request format

- README.md
Hey guys!
Thanks for working so hard on this list!  I've found a lot of stuff that's been really helpful to me on here.  I was hoping you might consider adding MockFive to the list.  It provides the ability to make mock objects in swift that support invocation logging and stubbing.
> Add MockFive

- README.md
iOS Interactive Side Menu (https://github.com/handsomecode/InteractiveSideMenu)
It supports following customization:
- Animation duration
- Visible content width
- Content scale
- Using spring animation with params customization
- Animation options like animation curve
> Add Interactive Side Menu

- README.md
EFQRCode - A better way to operate quick response code in Swift.
> Add EFQRCode

- README.md
https://github.com/LeonardoCardoso/SendIndicator
> Add SendIndicator

- README.md
https://github.com/LeonardoCardoso/SectionedSlider
> Add SectionedSlider - iOS 11 Control Center Slider

- README.md
Add **Cocoacasts** to **Swift Websites**.
> Add Cocoacasts

- README.md
Hi, 
I added `Gemini`. It is rich scroll based animation framework.
Thanks
[shoheiyokoyama/Gemini](https://github.com/shoheiyokoyama/Gemini)
> Add Gemini

- README.md
I know, another Layout framework, but this one is totally stateless, so it can be used with any other layout framework, including LayoutKit, SnapKit, Yoga Flexbox, ... The syntax is really simple, concise, readable and chainable.
See https://github.com/mirego/PinLayout for more information.
Thanks
> Add PinLayout layouting framework

- README.md
This will help people to start their own module Swift 3 projects.
> Add Swift 4 module template

- README.md
Please consider to add Swift 3 Module Template. It is a starting point for people that will create their own modules.
> Add: Swift 4 Module Template

- README.md
Added ReactiveAPI, a library which allows you to write clean, concise and declarative network code relying on URLSession, with the power of RxSwift. Inspired by Retrofit.
> Added ReactiveAPI

- README.md
Disclosure: I am the author / maintainer
> Add PostgresClientKit

- README.md
Bow is a library for Typed Functional Programming that includes multiple modules with Higher Kinded Types emulation, function manipulation utilities, data types, optics and many other features, as well as integrations with libraries like RxSwift and BrightFutures.
Website: https://bow-swift.io
Disclosure: I am the library creator.
> Add Bow library for Functional Programming

- README.md
Add SwiftyJSONAccelerator - macOS app to generate Swift 5 code for models from JSON (with Codeable)
> Add SwiftyJSONAccelerator

- README.md
A simple cross-platform toolbar/custom input accessory view library for iOS & macOS.
> Add Ribbon 🎀

- README.md
Add Sejima Framework in the UI library section
> Added Sejima library

- README.md
Swift coroutines for iOS and macOS
> Add SwiftCoroutine
